### ISSUE TITLE
Using mod pack on different server hosting sites

### ISSUE THREAD

**Issue by jayrsea** [SwanX1/SlightlyVanillaFlavoured#15]
Is the Slightly Vanilla Flavored mod pack only usable for certain minecraft server hosting sites? I am trying to use it on Apex Hosting, but it isn't on the available list. Is there a way to get it there to allow my server to play with this mod pack? I am trying to get a bunch of streamers' viewers the chance to play on a server like the Homies SMP server.

Please let me know :3

**Comment by SwanX1** [comment]
Hi there!
We have no restrictions on any hosting sites using the modpack, as long as credit is provided and it isn't modified. This issue is out of our hands, you'll have to contact Apex Hosting themselves.
