### ISSUE TITLE
Friend Cannot connect to LAN world.

### ISSUE THREAD

**Issue by power9765** [SwanX1/SlightlyVanillaFlavoured#4]
Whenever we try to play using LAN my friend will login to the game and then it will say they logged out and they get a message that says "internal server error". Mod pack version 2.0.0 and we removed the Dynamic surroundings which stopped the crashes that we were having.

**Comment by SwanX1** [comment]
Sorry, we can't help you with LAN worlds, as they have always been buggy with modpacks.

**Comment by UrufuShinjiro** [comment]
> Whenever we try to play using LAN my friend will login to the game and then it will say they logged out and they get a message that says "internal server error". Mod pack version 2.0.0 and we removed the Dynamic surroundings which stopped the crashes that we were having.

Did you ever figure this out, having the same issue, error java.net,socketexception io.netty.hnadler.codec
