### ISSUE TITLE
Issue with servers

### ISSUE THREAD

**Issue by Ja-Jarackus** [SwanX1/SlightlyVanillaFlavoured#5]
![image](https://user-images.githubusercontent.com/75582615/113643200-aea21880-9679-11eb-998e-2ae7a44f9261.png)
I've tried v 2.2.0 and v 2.0.0 for both my client and server and I get this issue even for the official server, my friend who I asked to try it also has the same issue on my server and the official, any idea how I would go about sorting this? I've reinstalled the pack for both versions and nothing changed.

**Comment by SwanX1** [comment]
This is not an issue with the modpack, you should be able to join the server anyways, Forge only says that because the server doesn't have client-sided mods.

**Comment by Ja-Jarackus** [comment]
Both me and my friend are unable to join as it immediately disconnects us from both my server and the official one.

**Comment by SwanX1** [comment]
The official server is still on version 1.16.4-1.0.1
