### ISSUE TITLE
Trouble while instaling

### ISSUE THREAD

**Issue by HyeroDrimm** [SwanX1/SlightlyVanillaFlavoured#6]
version: 2.2.0

> Cannot find file System.Linq.Enumerable+WhereSelectListIterator`2[Curse.Radium.Minecraft.Models.ManifestResource,System.Int32] for addon 441114 in database. Aborting installation.

This is error that shows up while i try to intall. Some one said this was problem with network but i installed other modpack without issues. The same problem shows up when trying to install your SlightlyCinnamonFlavoured, but not Harcore one.

**Comment by NubsicleMan** [comment]
Same thing with me

**Comment by SwanX1** [comment]
This is an issue with CurseForge, not the modpack.
