### ISSUE TITLE
Server spamming ERROR messages

### ISSUE THREAD

**Issue by mikolajww** [SwanX1/SlightlyVanillaFlavoured#7]
When running the server pack, the message 
[Server thread/ERROR] [minecraft/WorldSettingsImport]: Error adding element: Base value out of range: 256 [-10-128]
Is printed every few seconds to many times a second.

Doesn't seem to affect the gameplay but seems to cause lag.

What could be the issue?

**Comment by SwanX1** [comment]
Shouldn't cause any lag, please provide more information:
 - Modpack version
 - Forge version
 - Any additional mods you may have installed
 - A game log

**Comment by SwanX1** [comment]
Closing issue due to no further information provided.

**Comment by mikolajww** [comment]
Hi, sorry for late reply.
Version: 2.1.0
Forge: 36.1.0
Additional mods: AppleSkin, JourneyMap and Create updated to v0.3.1
[latest.log](https://github.com/SwanX1/SlightlyVanillaFlavoured/files/6330245/latest.log)

**Comment by mikolajww** [comment]
Hi, sorry for late reply.
Version: 2.1.0
Forge: 36.1.0
Additional mods: AppleSkin, JourneyMap and Create updated to v0.3.1
[latest.log](https://github.com/SwanX1/SlightlyVanillaFlavoured/files/6330840/latest.log)
