### ISSUE TITLE
Crashes When Starting

### ISSUE THREAD

**Issue by ch0xy** [SwanX1/SlightlyVanillaFlavoured#9]
I tried changing versions and everything.  I am currently set to the  Slightly_Vanilla_Flavoured-2.3.0 version.
[crash-2021-06-02_13.32.25-fml.txt](https://github.com/SwanX1/SlightlyVanillaFlavoured/files/6587324/crash-2021-06-02_13.32.25-fml.txt)

**Comment by SwanX1** [comment]
Hello! It seems that your modpack is modified, and the Client Tweaks mod is causing issues.

**Comment by ch0xy** [comment]
> Hello! It seems that your modpack is modified, and the Client Tweaks mod is causing issues.

I have tried to reinstall multiple times even to new profiles and it does the same thing.
